package com.todoapp.mobile.ui.common

import com.todoapp.mobile.R

/**
 * Source icon -> 8-Bit pixel variant. GENERATED by tools/genpixelicons.py — do not hand-edit;
 * re-run the tool after adding or removing an `ic_*` drawable.
 *
 * Library R fields are not compile-time constants, so this is a runtime map rather than a
 * `when` — which is also why it can be merged across modules.
 */
val AppPixelIcons: Map<Int, Int> = mapOf(
    com.todoapp.mobile.R.drawable.ic_calendar to com.todoapp.mobile.R.drawable.ic_pixel_calendar,
    com.todoapp.mobile.R.drawable.ic_chat to com.todoapp.mobile.R.drawable.ic_pixel_chat,
    com.todoapp.mobile.R.drawable.ic_custom to com.todoapp.mobile.R.drawable.ic_pixel_custom,
    com.todoapp.mobile.R.drawable.ic_flip_camera to com.todoapp.mobile.R.drawable.ic_pixel_flip_camera,
    com.todoapp.mobile.R.drawable.ic_groups to com.todoapp.mobile.R.drawable.ic_pixel_groups,
    com.todoapp.mobile.R.drawable.ic_home to com.todoapp.mobile.R.drawable.ic_pixel_home,
    com.todoapp.mobile.R.drawable.ic_journal to com.todoapp.mobile.R.drawable.ic_pixel_journal,
    com.todoapp.mobile.R.drawable.ic_lock to com.todoapp.mobile.R.drawable.ic_pixel_lock,
    com.todoapp.mobile.R.drawable.ic_logo to com.todoapp.mobile.R.drawable.ic_pixel_logo,
    com.todoapp.mobile.R.drawable.ic_logout to com.todoapp.mobile.R.drawable.ic_pixel_logout,
    com.todoapp.mobile.R.drawable.ic_mail_white to com.todoapp.mobile.R.drawable.ic_pixel_mail_white,
    com.todoapp.mobile.R.drawable.ic_mobile to com.todoapp.mobile.R.drawable.ic_pixel_mobile,
    com.todoapp.mobile.R.drawable.ic_overtime to com.todoapp.mobile.R.drawable.ic_pixel_overtime,
    com.todoapp.mobile.R.drawable.ic_person to com.todoapp.mobile.R.drawable.ic_pixel_person,
    com.todoapp.mobile.R.drawable.ic_secret_mode to com.todoapp.mobile.R.drawable.ic_pixel_secret_mode,
    com.todoapp.mobile.R.drawable.ic_selected_calendar to com.todoapp.mobile.R.drawable.ic_pixel_selected_calendar,
    com.todoapp.mobile.R.drawable.ic_selected_chat to com.todoapp.mobile.R.drawable.ic_pixel_selected_chat,
    com.todoapp.mobile.R.drawable.ic_selected_groups to com.todoapp.mobile.R.drawable.ic_pixel_selected_groups,
    com.todoapp.mobile.R.drawable.ic_selected_home to com.todoapp.mobile.R.drawable.ic_pixel_selected_home,
    com.todoapp.mobile.R.drawable.ic_selected_statistic to com.todoapp.mobile.R.drawable.ic_pixel_selected_statistic,
    com.todoapp.mobile.R.drawable.ic_settings_accessibility to com.todoapp.mobile.R.drawable.ic_pixel_settings_accessibility,
    com.todoapp.mobile.R.drawable.ic_settings_block to com.todoapp.mobile.R.drawable.ic_pixel_settings_block,
    com.todoapp.mobile.R.drawable.ic_settings_bug to com.todoapp.mobile.R.drawable.ic_pixel_settings_bug,
    com.todoapp.mobile.R.drawable.ic_settings_camera to com.todoapp.mobile.R.drawable.ic_pixel_settings_camera,
    com.todoapp.mobile.R.drawable.ic_settings_document to com.todoapp.mobile.R.drawable.ic_pixel_settings_document,
    com.todoapp.mobile.R.drawable.ic_settings_download to com.todoapp.mobile.R.drawable.ic_pixel_settings_download,
    com.todoapp.mobile.R.drawable.ic_settings_sound to com.todoapp.mobile.R.drawable.ic_pixel_settings_sound,
    com.todoapp.mobile.R.drawable.ic_staged to com.todoapp.mobile.R.drawable.ic_pixel_staged,
    com.todoapp.mobile.R.drawable.ic_statistic to com.todoapp.mobile.R.drawable.ic_pixel_statistic,
    com.todoapp.mobile.R.drawable.ic_visibility_close to com.todoapp.mobile.R.drawable.ic_pixel_visibility_close,
    com.todoapp.mobile.R.drawable.ic_visibility_on to com.todoapp.mobile.R.drawable.ic_pixel_visibility_on,
)
