package com.todoapp.mobile.ui.common

import com.todoapp.mobile.R

/**
 * Source icon -> 8-Bit pixel variant. GENERATED by tools/genpixelicons.py — do not hand-edit;
 * re-run the tool after adding or removing an `ic_*` drawable.
 *
 * Library R fields are not compile-time constants, so this is a runtime map rather than a
 * `when` — which is also why it can be merged across modules.
 */
val AppPixelIcons: Map<Int, Int> = mapOf(
    R.drawable.ic_calendar to R.drawable.ic_pixel_calendar,
    R.drawable.ic_chat to R.drawable.ic_pixel_chat,
    R.drawable.ic_custom to R.drawable.ic_pixel_custom,
    R.drawable.ic_flip_camera to R.drawable.ic_pixel_flip_camera,
    R.drawable.ic_groups to R.drawable.ic_pixel_groups,
    R.drawable.ic_home to R.drawable.ic_pixel_home,
    R.drawable.ic_journal to R.drawable.ic_pixel_journal,
    R.drawable.ic_lock to R.drawable.ic_pixel_lock,
    R.drawable.ic_logo to R.drawable.ic_pixel_logo,
    R.drawable.ic_logout to R.drawable.ic_pixel_logout,
    R.drawable.ic_mail_white to R.drawable.ic_pixel_mail_white,
    R.drawable.ic_mobile to R.drawable.ic_pixel_mobile,
    R.drawable.ic_overtime to R.drawable.ic_pixel_overtime,
    R.drawable.ic_person to R.drawable.ic_pixel_person,
    R.drawable.ic_secret_mode to R.drawable.ic_pixel_secret_mode,
    R.drawable.ic_selected_calendar to R.drawable.ic_pixel_selected_calendar,
    R.drawable.ic_selected_chat to R.drawable.ic_pixel_selected_chat,
    R.drawable.ic_selected_groups to R.drawable.ic_pixel_selected_groups,
    R.drawable.ic_selected_home to R.drawable.ic_pixel_selected_home,
    R.drawable.ic_selected_statistic to R.drawable.ic_pixel_selected_statistic,
    R.drawable.ic_settings_accessibility to R.drawable.ic_pixel_settings_accessibility,
    R.drawable.ic_settings_block to R.drawable.ic_pixel_settings_block,
    R.drawable.ic_settings_bug to R.drawable.ic_pixel_settings_bug,
    R.drawable.ic_settings_camera to R.drawable.ic_pixel_settings_camera,
    R.drawable.ic_settings_document to R.drawable.ic_pixel_settings_document,
    R.drawable.ic_settings_download to R.drawable.ic_pixel_settings_download,
    R.drawable.ic_settings_sound to R.drawable.ic_pixel_settings_sound,
    R.drawable.ic_staged to R.drawable.ic_pixel_staged,
    R.drawable.ic_statistic to R.drawable.ic_pixel_statistic,
    R.drawable.ic_visibility_close to R.drawable.ic_pixel_visibility_close,
    R.drawable.ic_visibility_on to R.drawable.ic_pixel_visibility_on,
)
