package com.todoapp.uikit.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

// Default palette is ORIGINAL (see PaletteRepository); TDTheme swaps the provided kit at runtime.
internal val LocalLightColors = staticCompositionLocalOf { defaultLightColors() }
internal val LocalDarkColors = staticCompositionLocalOf { defaultDarkColors() }

internal fun monochromeLightColors(
    // Monochrome (Notion-style): neutral black/gray/white chrome + grid (primary/nav are neutral).
    // The app's CHARACTERISTIC semantic accents are kept: blue (`purple`) for one-time tasks,
    // orange (warm family) for pomodoro/reminders/warnings, green for done, red for error/overdue.
    infoCardBgColor: Color = Color(0xFFF0F0F0),
    groupMemberCardBgColor: Color = Color(0xFFF0F0F0),
    groupTaskFilterColor: Color = Color(0xFFDC2626),
    lightRed: Color = Color(0xFFFCE4E3),
    red: Color = Color(0xFFE3A7AA),
    crossRed: Color = Color(0xFFDC2626),
    heartFull: Color = Color(0xFFC0392B),
    heartEmpty: Color = Color(0xFFC8C8C8),
    statusCardGray: Color = Color(0xFF6E6E6E),
    bgColorPurple: Color = Color(0xFFF0F0F0),
    bgColor: Color = Color(0xFFFFFFFF),
    background: Color = bgColor,
    gridLine: Color = Color(0xFFF1F1F1),
    onBackground: Color = Color(0xFF1A1A1A),
    surface: Color = Color(0xFFFFFFFF),
    onSurface: Color = Color(0xFF1A1A1A),
    primary: Color = Color(0xFF1A1A1A),
    onPrimary: Color = Color(0xFFFFFFFF),
    lightPurple: Color = Color(0xFFD8D8D8),
    gray: Color = Color(0xFF5F5F5F),
    black: Color = Color(0xFF1A1A1A),
    darkPurple: Color = Color(0xFF2A4FB0),
    purple: Color = Color(0xFF3B6FE0),
    brown: Color = Color(0xFF5F5F5F),
    green: Color = Color(0xFF16A34A),
    lightGreen: Color = Color(0xFFDCFCE7),
    mediumGreen: Color = Color(0xFF16A34A),
    darkGreen: Color = Color(0xFF15803D),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF6E6E6E),
    lightBrown: Color = Color(0xFFD8D8D8),
    beige: Color = Color(0xFFEDECEA),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF8E1),
    lightPending: Color = Color(0xFFF5F5F5),
    mediumPending: Color = Color(0xFF808080),
    pendingGray: Color = Color(0xFF5F5F5F),
    darkPending: Color = Color(0xFF3D3D3D),
    white: Color = Color(0xFFFFFFFF),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFFE2E2E2),
    warmContainer: Color = Color(0xFFFFE2CD),
    purpleContainer: Color = Color(0xFFE6EDFC),
    settingsCard: Color = Color(0xFFFFFFFF),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun monochromeDarkColors(
    // Monochrome dark: neutral near-black chrome + gray grid; characteristic accents kept
    // (blue=one-time via `purple`, orange=pomodoro/reminders, green=done, red=error). Every neutral
    // is a DELIBERATE dark value (a gray that reads on light must invert here).
    infoCardBgColor: Color = Color(0xFF1C1C1C),
    groupMemberCardBgColor: Color = Color(0xFF232323),
    groupTaskFilterColor: Color = Color(0xFFF26D66),
    lightRed: Color = Color(0xFF4A1D1D),
    red: Color = Color(0xFFC98B8F),
    crossRed: Color = Color(0xFFF26D66),
    heartFull: Color = Color(0xFFE5645C),
    heartEmpty: Color = Color(0xFF3A3A3A),
    statusCardGray: Color = Color(0xFF909090),
    bgColorPurple: Color = Color(0xFF202020),
    bgColor: Color = Color(0xFF0D0D0D),
    background: Color = Color(0xFF0D0D0D),
    gridLine: Color = Color(0xFF1E1E1E),
    onBackground: Color = Color(0xFFEDEDED),
    surface: Color = Color(0xFF1A1A1A),
    onSurface: Color = Color(0xFFEDEDED),
    primary: Color = Color(0xFFEDEDED),
    onPrimary: Color = Color(0xFF0D0D0D),
    lightPurple: Color = Color(0xFF3A3A3A),
    gray: Color = Color(0xFFB0B0B0),
    black: Color = Color(0xFF000000),
    darkPurple: Color = Color(0xFF93B4F5),
    purple: Color = Color(0xFF5B8DEF),
    brown: Color = Color(0xFFA0A0A0),
    green: Color = Color(0xFF4ADE80),
    lightGreen: Color = Color(0xFF14311F),
    mediumGreen: Color = Color(0xFF4ADE80),
    darkGreen: Color = Color(0xFF86EFAC),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF909090),
    lightBrown: Color = Color(0xFF3A3A3A),
    beige: Color = Color(0xFF2A2A2A),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF5E0),
    lightPending: Color = Color(0xFF1A1A1A),
    mediumPending: Color = Color(0xFF808080),
    pendingGray: Color = Color(0xFFB0B0B0),
    darkPending: Color = Color(0xFFD0D0D0),
    white: Color = Color(0xFFFFFFFF),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFF2A2A2A),
    warmContainer: Color = Color(0xFF3A2A1E),
    purpleContainer: Color = Color(0xFF1E2A4A),
    settingsCard: Color = Color(0xFF161616),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun defaultLightColors(
    // Original kit: the app's classic purple/blue palette (pre-monochrome). gridLine is
    // Transparent so the graph-paper grid disappears for this kit.
    infoCardBgColor: Color = Color(0xFFEEF2FF),
    groupMemberCardBgColor: Color = Color(0xFFEBEBEB),
    groupTaskFilterColor: Color = Color(0xFFFF0000),
    lightRed: Color = Color(0xFFFFE6E7),
    red: Color = Color(0xFFFFB1B5),
    crossRed: Color = Color(0xFFB2282D),
    heartFull: Color = Color(0xFFB2282D),
    heartEmpty: Color = Color(0xFFC0C0C0),
    statusCardGray: Color = Color(0xFF6E7180),
    bgColorPurple: Color = Color(0xFFEFF2FF),
    bgColor: Color = Color(0xFFF8F8F8),
    background: Color = bgColor,
    gridLine: Color = Color.Transparent,
    onBackground: Color = Color(0xFF090E23),
    surface: Color = Color(0xFFF8F8F8),
    onSurface: Color = Color(0xFF090E23),
    primary: Color = Color(0xFF4566EC),
    onPrimary: Color = Color(0xFFFFFAF0),
    lightPurple: Color = Color(0xFFA9BAFF),
    gray: Color = Color(0xFF717171),
    black: Color = Color(0xFF090E23),
    darkPurple: Color = Color(0xFF1C3082),
    purple: Color = Color(0xFF4566EC),
    brown: Color = Color(0xFF3F2D20),
    green: Color = Color(0xFF2AE35A),
    lightGreen: Color = Color(0xFFE8F5E9),
    mediumGreen: Color = Color(0xFF81C784),
    darkGreen: Color = Color(0xFF2E7D32),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF73665C),
    lightBrown: Color = Color(0xFFD3BBAA),
    beige: Color = Color(0xFFE6DCCD),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF8E1),
    lightPending: Color = Color(0xFFEDF4FF),
    mediumPending: Color = Color(0xFF4E90C4),
    pendingGray: Color = Color(0xFF7A9CC6),
    darkPending: Color = Color(0xFF3D6A9E),
    white: Color = Color(0xFFFFFAF0),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFFC0C0C0),
    warmContainer: Color = Color(0xFFFFE2CD),
    purpleContainer: Color = Color(0xFFECE7FF),
    settingsCard: Color = Color(0xFFFFFFFF),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun defaultDarkColors(
    // Original kit — dark. gridLine Transparent (no grid).
    infoCardBgColor: Color = Color(0xFF1E2240),
    groupMemberCardBgColor: Color = Color(0xFF232323),
    groupTaskFilterColor: Color = Color(0xFFFF0000),
    lightRed: Color = Color(0xFF7A1F2B),
    red: Color = Color(0xFFFFB1B5),
    crossRed: Color = Color(0xFFCF6679),
    heartFull: Color = Color(0xFFCF6679),
    heartEmpty: Color = Color(0xFF444444),
    statusCardGray: Color = Color(0xFF898DA1),
    bgColorPurple: Color = Color(0xFF2B2F5E),
    bgColor: Color = Color(0xFF121212),
    background: Color = Color(0xFF16171B),
    gridLine: Color = Color.Transparent,
    onBackground: Color = Color(0xFFE1E1E1),
    surface: Color = Color(0xFF1E1E1E),
    onSurface: Color = Color(0xFFE1E1E1),
    primary: Color = Color(0xFF6C8AFF),
    onPrimary: Color = Color(0xFF000000),
    lightPurple: Color = Color(0xFFA9BAFF),
    gray: Color = Color(0xFF9E9E9E),
    black: Color = Color(0xFF000000),
    darkPurple: Color = Color(0xFF1C3082),
    purple: Color = Color(0xFF4566EC),
    brown: Color = Color(0xFF3F2D20),
    green: Color = Color(0xFF84BD93),
    lightGreen: Color = Color(0xFF1B3A1E),
    mediumGreen: Color = Color(0xFF4CAF50),
    darkGreen: Color = Color(0xFFA5D6A7),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF73665C),
    lightBrown: Color = Color(0xFFD3BBAA),
    beige: Color = Color(0xFFE6DCCD),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF5E0),
    lightPending: Color = Color(0xFF1A2537),
    mediumPending: Color = Color(0xFF3A93DB),
    pendingGray: Color = Color(0xFF6B8DB5),
    darkPending: Color = Color(0xFF9BBDE0),
    white: Color = Color(0xFFFFFAF0),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFF444444),
    warmContainer: Color = Color(0xFF3A2A1E),
    purpleContainer: Color = Color(0xFF2B2F5E),
    settingsCard: Color = Color(0xFF212229),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

@Immutable
data class TDColor(
    val infoCardBgColor: Color,
    val groupMemberCardBgColor: Color,
    val groupTaskFilterColor: Color,
    val lightRed: Color,
    val red: Color,
    val crossRed: Color,
    val heartFull: Color,
    val heartEmpty: Color,
    val statusCardGray: Color,
    val bgColorPurple: Color,
    val bgColor: Color,
    val background: Color,
    val gridLine: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val primary: Color,
    val onPrimary: Color,
    val lightPurple: Color,
    val gray: Color,
    val black: Color,
    val darkPurple: Color,
    val purple: Color,
    val brown: Color,
    val green: Color,
    val lightGreen: Color,
    val mediumGreen: Color,
    val darkGreen: Color,
    val orange: Color,
    val darkBrown: Color,
    val lightBrown: Color,
    val beige: Color,
    val lightOrange: Color,
    val lightYellow: Color,
    val lightPending: Color,
    val mediumPending: Color,
    val pendingGray: Color,
    val darkPending: Color,
    val white: Color,
    val softPink: Color,
    val lightGray: Color,
    val warmContainer: Color,
    val purpleContainer: Color,
    val settingsCard: Color,
    val polaroid: PolaroidColors,
)
