package com.todoapp.uikit.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

// Default palette is ORIGINAL (see PaletteRepository); TDTheme swaps the provided kit at runtime.
internal val LocalLightColors = staticCompositionLocalOf { defaultLightColors() }
internal val LocalDarkColors = staticCompositionLocalOf { defaultDarkColors() }

internal fun monochromeLightColors(
    // Monochrome (Notion-style): neutral black/gray/white chrome + grid (primary/nav are neutral).
    // The app's CHARACTERISTIC semantic accents are kept: blue (`purple`) for one-time tasks,
    // orange (warm family) for pomodoro/reminders/warnings, green for done, red for error/overdue.
    infoCardBgColor: Color = Color(0xFFF0F0F0),
    groupMemberCardBgColor: Color = Color(0xFFF0F0F0),
    groupTaskFilterColor: Color = Color(0xFFDC2626),
    lightRed: Color = Color(0xFFFCE4E3),
    red: Color = Color(0xFFE3A7AA),
    crossRed: Color = Color(0xFFDC2626),
    heartFull: Color = Color(0xFFC0392B),
    heartEmpty: Color = Color(0xFFC8C8C8),
    statusCardGray: Color = Color(0xFF6E6E6E),
    bgColorPurple: Color = Color(0xFFF0F0F0),
    bgColor: Color = Color(0xFFFFFFFF),
    background: Color = bgColor,
    gridLine: Color = Color(0xFFF1F1F1),
    onBackground: Color = Color(0xFF1A1A1A),
    surface: Color = Color(0xFFFFFFFF),
    onSurface: Color = Color(0xFF1A1A1A),
    primary: Color = Color(0xFF1A1A1A),
    onPrimary: Color = Color(0xFFFFFFFF),
    lightPurple: Color = Color(0xFFD8D8D8),
    gray: Color = Color(0xFF5F5F5F),
    black: Color = Color(0xFF1A1A1A),
    darkPurple: Color = Color(0xFF2A4FB0),
    purple: Color = Color(0xFF3B6FE0),
    brown: Color = Color(0xFF5F5F5F),
    green: Color = Color(0xFF16A34A),
    lightGreen: Color = Color(0xFFDCFCE7),
    mediumGreen: Color = Color(0xFF16A34A),
    darkGreen: Color = Color(0xFF15803D),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF6E6E6E),
    lightBrown: Color = Color(0xFFD8D8D8),
    beige: Color = Color(0xFFEDECEA),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF8E1),
    lightPending: Color = Color(0xFFF5F5F5),
    mediumPending: Color = Color(0xFF808080),
    pendingGray: Color = Color(0xFF5F5F5F),
    darkPending: Color = Color(0xFF3D3D3D),
    white: Color = Color(0xFFFFFFFF),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFFE2E2E2),
    warmContainer: Color = Color(0xFFFFE2CD),
    purpleContainer: Color = Color(0xFFE6EDFC),
    settingsCard: Color = Color(0xFFFFFFFF),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun monochromeDarkColors(
    // Monochrome dark: neutral near-black chrome + gray grid; characteristic accents kept
    // (blue=one-time via `purple`, orange=pomodoro/reminders, green=done, red=error). Every neutral
    // is a DELIBERATE dark value (a gray that reads on light must invert here).
    infoCardBgColor: Color = Color(0xFF1C1C1C),
    groupMemberCardBgColor: Color = Color(0xFF232323),
    groupTaskFilterColor: Color = Color(0xFFF26D66),
    lightRed: Color = Color(0xFF4A1D1D),
    red: Color = Color(0xFFC98B8F),
    crossRed: Color = Color(0xFFF26D66),
    heartFull: Color = Color(0xFFE5645C),
    heartEmpty: Color = Color(0xFF3A3A3A),
    statusCardGray: Color = Color(0xFF909090),
    bgColorPurple: Color = Color(0xFF202020),
    bgColor: Color = Color(0xFF0D0D0D),
    background: Color = Color(0xFF0D0D0D),
    gridLine: Color = Color(0xFF1E1E1E),
    onBackground: Color = Color(0xFFEDEDED),
    surface: Color = Color(0xFF1A1A1A),
    onSurface: Color = Color(0xFFEDEDED),
    primary: Color = Color(0xFFEDEDED),
    onPrimary: Color = Color(0xFF0D0D0D),
    lightPurple: Color = Color(0xFF3A3A3A),
    gray: Color = Color(0xFFB0B0B0),
    black: Color = Color(0xFF000000),
    darkPurple: Color = Color(0xFF93B4F5),
    purple: Color = Color(0xFF5B8DEF),
    brown: Color = Color(0xFFA0A0A0),
    green: Color = Color(0xFF4ADE80),
    lightGreen: Color = Color(0xFF14311F),
    mediumGreen: Color = Color(0xFF4ADE80),
    darkGreen: Color = Color(0xFF86EFAC),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF909090),
    lightBrown: Color = Color(0xFF3A3A3A),
    beige: Color = Color(0xFF2A2A2A),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF5E0),
    lightPending: Color = Color(0xFF1A1A1A),
    mediumPending: Color = Color(0xFF808080),
    pendingGray: Color = Color(0xFFB0B0B0),
    darkPending: Color = Color(0xFFD0D0D0),
    white: Color = Color(0xFFFFFFFF),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFF2A2A2A),
    warmContainer: Color = Color(0xFF3A2A1E),
    purpleContainer: Color = Color(0xFF1E2A4A),
    settingsCard: Color = Color(0xFF161616),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun defaultLightColors(
    // Original kit: the app's classic purple/blue palette (pre-monochrome). gridLine is
    // Transparent so the graph-paper grid disappears for this kit.
    infoCardBgColor: Color = Color(0xFFEEF2FF),
    groupMemberCardBgColor: Color = Color(0xFFEBEBEB),
    groupTaskFilterColor: Color = Color(0xFFFF0000),
    lightRed: Color = Color(0xFFFFE6E7),
    red: Color = Color(0xFFFFB1B5),
    crossRed: Color = Color(0xFFB2282D),
    heartFull: Color = Color(0xFFB2282D),
    heartEmpty: Color = Color(0xFFC0C0C0),
    statusCardGray: Color = Color(0xFF6E7180),
    bgColorPurple: Color = Color(0xFFEFF2FF),
    bgColor: Color = Color(0xFFF8F8F8),
    background: Color = bgColor,
    gridLine: Color = Color.Transparent,
    onBackground: Color = Color(0xFF090E23),
    surface: Color = Color(0xFFF8F8F8),
    onSurface: Color = Color(0xFF090E23),
    primary: Color = Color(0xFF4566EC),
    onPrimary: Color = Color(0xFFFFFAF0),
    lightPurple: Color = Color(0xFFA9BAFF),
    gray: Color = Color(0xFF717171),
    black: Color = Color(0xFF090E23),
    darkPurple: Color = Color(0xFF1C3082),
    purple: Color = Color(0xFF4566EC),
    brown: Color = Color(0xFF3F2D20),
    green: Color = Color(0xFF2AE35A),
    lightGreen: Color = Color(0xFFE8F5E9),
    mediumGreen: Color = Color(0xFF81C784),
    darkGreen: Color = Color(0xFF2E7D32),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF73665C),
    lightBrown: Color = Color(0xFFD3BBAA),
    beige: Color = Color(0xFFE6DCCD),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF8E1),
    lightPending: Color = Color(0xFFEDF4FF),
    mediumPending: Color = Color(0xFF4E90C4),
    pendingGray: Color = Color(0xFF7A9CC6),
    darkPending: Color = Color(0xFF3D6A9E),
    white: Color = Color(0xFFFFFAF0),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFFC0C0C0),
    warmContainer: Color = Color(0xFFFFE2CD),
    purpleContainer: Color = Color(0xFFECE7FF),
    settingsCard: Color = Color(0xFFFFFFFF),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun defaultDarkColors(
    // Original kit — dark. gridLine Transparent (no grid).
    infoCardBgColor: Color = Color(0xFF1E2240),
    groupMemberCardBgColor: Color = Color(0xFF232323),
    groupTaskFilterColor: Color = Color(0xFFFF0000),
    lightRed: Color = Color(0xFF7A1F2B),
    red: Color = Color(0xFFFFB1B5),
    crossRed: Color = Color(0xFFCF6679),
    heartFull: Color = Color(0xFFCF6679),
    heartEmpty: Color = Color(0xFF444444),
    statusCardGray: Color = Color(0xFF898DA1),
    bgColorPurple: Color = Color(0xFF2B2F5E),
    bgColor: Color = Color(0xFF121212),
    background: Color = Color(0xFF16171B),
    gridLine: Color = Color.Transparent,
    onBackground: Color = Color(0xFFE1E1E1),
    surface: Color = Color(0xFF1E1E1E),
    onSurface: Color = Color(0xFFE1E1E1),
    primary: Color = Color(0xFF6C8AFF),
    onPrimary: Color = Color(0xFF000000),
    lightPurple: Color = Color(0xFFA9BAFF),
    gray: Color = Color(0xFF9E9E9E),
    black: Color = Color(0xFF000000),
    darkPurple: Color = Color(0xFF1C3082),
    purple: Color = Color(0xFF4566EC),
    brown: Color = Color(0xFF3F2D20),
    green: Color = Color(0xFF84BD93),
    lightGreen: Color = Color(0xFF1B3A1E),
    mediumGreen: Color = Color(0xFF4CAF50),
    darkGreen: Color = Color(0xFFA5D6A7),
    orange: Color = Color(0xFFEF8829),
    darkBrown: Color = Color(0xFF73665C),
    lightBrown: Color = Color(0xFFD3BBAA),
    beige: Color = Color(0xFFE6DCCD),
    lightOrange: Color = Color(0xFFFFE2CD),
    lightYellow: Color = Color(0xFFFFF5E0),
    lightPending: Color = Color(0xFF1A2537),
    mediumPending: Color = Color(0xFF3A93DB),
    pendingGray: Color = Color(0xFF6B8DB5),
    darkPending: Color = Color(0xFF9BBDE0),
    white: Color = Color(0xFFFFFAF0),
    softPink: Color = Color(0xFFF5D3BB),
    lightGray: Color = Color(0xFF444444),
    warmContainer: Color = Color(0xFF3A2A1E),
    purpleContainer: Color = Color(0xFF2B2F5E),
    settingsCard: Color = Color(0xFF212229),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun pixelLightColors(
    // 8-Bit light: an NES cartridge manual — paper-white ground, hard black ink, and the saturated
    // 2C02 hues (red #D82800, blue #0058F8, green #00A800, yellow #FCE000). Unlike MONOCHROME this
    // kit is deliberately chromatic: an 8-bit palette is small, not desaturated.
    //
    // `lightGray` is near-black on purpose. It is this app's hairline-border token (58 sites, mostly
    // `.border(1.dp, lightGray, …)` and `unfocusedBorderColor`), so darkening it turns every card
    // edge into a crisp pixel outline for free, while the many `.copy(alpha = 0.2f)` call sites
    // still resolve to soft grays.
    infoCardBgColor: Color = Color(0xFFD8E4FC),
    groupMemberCardBgColor: Color = Color(0xFFE4E4E4),
    groupTaskFilterColor: Color = Color(0xFFD82800),
    lightRed: Color = Color(0xFFF8C8B8),
    red: Color = Color(0xFFE87868),
    crossRed: Color = Color(0xFFD82800),
    heartFull: Color = Color(0xFFD82800),
    heartEmpty: Color = Color(0xFFBCBCBC),
    statusCardGray: Color = Color(0xFF7C7C7C),
    bgColorPurple: Color = Color(0xFFE4E4E4),
    bgColor: Color = Color(0xFFF8F8F8),
    background: Color = bgColor,
    // Dither covers half the surface, so it needs far less contrast than a hairline lattice would.
    gridLine: Color = Color(0xFFEFEFEF),
    onBackground: Color = Color(0xFF0F0F0F),
    surface: Color = Color(0xFFFCFCFC),
    onSurface: Color = Color(0xFF0F0F0F),
    primary: Color = Color(0xFF0058F8),
    onPrimary: Color = Color(0xFFFCFCFC),
    lightPurple: Color = Color(0xFFB8B8F8),
    gray: Color = Color(0xFF7C7C7C),
    black: Color = Color(0xFF0F0F0F),
    darkPurple: Color = Color(0xFF4428BC),
    purple: Color = Color(0xFF0058F8),
    brown: Color = Color(0xFF883400),
    green: Color = Color(0xFF00A800),
    lightGreen: Color = Color(0xFFD8F0B8),
    mediumGreen: Color = Color(0xFF00A800),
    darkGreen: Color = Color(0xFF006800),
    orange: Color = Color(0xFFE45C10),
    darkBrown: Color = Color(0xFF503000),
    lightBrown: Color = Color(0xFFC87038),
    beige: Color = Color(0xFFF8D8B0),
    lightOrange: Color = Color(0xFFFCD8B0),
    lightYellow: Color = Color(0xFFFCF0B8),
    lightPending: Color = Color(0xFFE4E4E4),
    mediumPending: Color = Color(0xFFA8A8A8),
    pendingGray: Color = Color(0xFF7C7C7C),
    darkPending: Color = Color(0xFF4A4A4A),
    white: Color = Color(0xFFFCFCFC),
    softPink: Color = Color(0xFFF878F8),
    lightGray: Color = Color(0xFF0F0F0F),
    warmContainer: Color = Color(0xFFFCD8B0),
    purpleContainer: Color = Color(0xFFC8DCFC),
    settingsCard: Color = Color(0xFFFCFCFC),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun pixelDarkColors(
    // 8-Bit dark: a CRT in a dark room — near-black ground with a faint blue cast, scanline grid, and
    // the bright end of the NES ramp (sky blue #3CBCFC, lime #B8F818, salmon #F87858) which is what
    // those hues actually looked like on a phosphor screen.
    //
    // Tokens whose NAME says "light"/"dark" invert here exactly as they do in `monochromeDarkColors`:
    // `darkGreen`/`darkPurple`/`darkPending`/`darkBrown` are used as INK, so they must be lighter
    // than their mid siblings, while `lightGreen`/`lightRed`/`lightPending` are FILLS and go dark.
    infoCardBgColor: Color = Color(0xFF1C2438),
    groupMemberCardBgColor: Color = Color(0xFF202028),
    groupTaskFilterColor: Color = Color(0xFFF87858),
    lightRed: Color = Color(0xFF3A1810),
    red: Color = Color(0xFFE87868),
    crossRed: Color = Color(0xFFF87858),
    heartFull: Color = Color(0xFFF87858),
    heartEmpty: Color = Color(0xFF3A3A48),
    statusCardGray: Color = Color(0xFFA8A8B8),
    bgColorPurple: Color = Color(0xFF202028),
    bgColor: Color = Color(0xFF0F0F18),
    background: Color = Color(0xFF0F0F18),
    gridLine: Color = Color(0xFF15151F),
    onBackground: Color = Color(0xFFFCFCFC),
    surface: Color = Color(0xFF1A1A24),
    onSurface: Color = Color(0xFFFCFCFC),
    primary: Color = Color(0xFF3CBCFC),
    onPrimary: Color = Color(0xFF0F0F18),
    lightPurple: Color = Color(0xFF2A2A48),
    gray: Color = Color(0xFFA8A8B8),
    black: Color = Color(0xFF000000),
    darkPurple: Color = Color(0xFF8CD8FC),
    purple: Color = Color(0xFF3CBCFC),
    brown: Color = Color(0xFFC87038),
    green: Color = Color(0xFFB8F818),
    lightGreen: Color = Color(0xFF1A3A18),
    mediumGreen: Color = Color(0xFFB8F818),
    darkGreen: Color = Color(0xFFD8F8B8),
    orange: Color = Color(0xFFFCA044),
    darkBrown: Color = Color(0xFFC8A078),
    lightBrown: Color = Color(0xFF3A3028),
    beige: Color = Color(0xFF3A3020),
    lightOrange: Color = Color(0xFFFCD8B0),
    lightYellow: Color = Color(0xFFFCF0B8),
    lightPending: Color = Color(0xFF202028),
    mediumPending: Color = Color(0xFF6C6C7C),
    pendingGray: Color = Color(0xFFA8A8B8),
    darkPending: Color = Color(0xFFD8D8E0),
    white: Color = Color(0xFFFCFCFC),
    softPink: Color = Color(0xFFF878F8),
    lightGray: Color = Color(0xFF8C8CA8),
    warmContainer: Color = Color(0xFF3A2410),
    purpleContainer: Color = Color(0xFF16243E),
    settingsCard: Color = Color(0xFF1A1A24),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun terminalLightColors(
    // Terminal light: a phosphor printout — faintly green paper, near-black green ink, and a green
    // walked down the luminance ramp until a white button label clears AA. The obvious "terminal
    // green" #0E8A2E sits at the midpoint and fails against black and white alike.
    //
    // The accents are re-pointed, not just re-tinted: `primary` is the phosphor green, and the whole
    // `*Green` family — the app's only expression of "done" — becomes CYAN, so success never
    // collides with the primary. `orange` and `purple` are deepened because both are used as INK
    // (DetailsScreen, ChatErrorBanner, AlarmSoundsScreen), where the dark-mode values are unreadable.
    //
    // `lightGray` is the hairline-border token (63 sites, mostly `.border(1.dp, lightGray, …)`), so a
    // mid green there draws every card edge as a phosphor rule for free. `lightPurple` is green for a
    // less obvious reason: it is at once the chat bubble FILL and the task-card outline at
    // `.copy(alpha = 0.3f)`, and a violet at that alpha over a green card is mud.
    infoCardBgColor: Color = Color(0xFFE2F1E0),
    groupMemberCardBgColor: Color = Color(0xFFE9F5E8),
    groupTaskFilterColor: Color = Color(0xFFC41E1E),
    lightRed: Color = Color(0xFFFBE0E0),
    red: Color = Color(0xFFD14545),
    crossRed: Color = Color(0xFFC41E1E),
    heartFull: Color = Color(0xFFC41E1E),
    heartEmpty: Color = Color(0xFFC3D6C0),
    statusCardGray: Color = Color(0xFF4F7A4A),
    bgColorPurple: Color = Color(0xFFE6F6EA),
    bgColor: Color = Color(0xFFF3FAF2),
    background: Color = bgColor,
    // The daylight scanline: a ruled band one notch off the paper. Deliberately near-invisible.
    gridLine: Color = Color(0xFFDCEEDA),
    onBackground: Color = Color(0xFF0B1A0C),
    surface: Color = Color(0xFFFBFEFA),
    onSurface: Color = Color(0xFF0B1A0C),
    primary: Color = Color(0xFF0B7A28),
    onPrimary: Color = Color(0xFFF3FAF2),
    // Not violet: see the header. Mid phosphor green, so it survives both of its roles.
    lightPurple: Color = Color(0xFF9FD4AB),
    gray: Color = Color(0xFF4F7A4A),
    black: Color = Color(0xFF0B1A0C),
    darkPurple: Color = Color(0xFF5B21B6),
    purple: Color = Color(0xFF7C3AED),
    brown: Color = Color(0xFF2F5E2B),
    // Restful-positive (long break, strong password, online dot) rather than "done" — stays green.
    green: Color = Color(0xFF0B7A28),
    lightGreen: Color = Color(0xFFD6F0F7),
    mediumGreen: Color = Color(0xFF0B647C),
    darkGreen: Color = Color(0xFF084D5F),
    orange: Color = Color(0xFF8F5B00),
    darkBrown: Color = Color(0xFF1E4620),
    lightBrown: Color = Color(0xFF4F7A4A),
    beige: Color = Color(0xFFE8F3E6),
    lightOrange: Color = Color(0xFFFBEFCF),
    lightYellow: Color = Color(0xFFF7F3D4),
    lightPending: Color = Color(0xFFE9F5E8),
    mediumPending: Color = Color(0xFF7FA87A),
    // Takes hardcoded white text (TDGeneralProgressBar) and a background-tinted plus (TDAddTaskButton)
    // as well as reading as ink on paper, so it cannot drift far in either direction.
    pendingGray: Color = Color(0xFF2F6B3E),
    darkPending: Color = Color(0xFF14532D),
    white: Color = Color(0xFFFBFEFA),
    softPink: Color = Color(0xFFC0187A),
    lightGray: Color = Color(0xFF4E9A63),
    warmContainer: Color = Color(0xFFFBEFCF),
    purpleContainer: Color = Color(0xFFEDE4FD),
    settingsCard: Color = Color(0xFFFBFEFA),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

internal fun terminalDarkColors(
    // Terminal dark: the CRT itself — near-black ground, phosphor text, and the acid green a P1
    // phosphor actually threw. Card separation comes entirely from the `lightGray` hairline: this kit
    // keeps SOFT elevation, and a blurred shadow is invisible against #050705.
    //
    // Tokens whose NAME says light/dark invert here exactly as in `pixelDarkColors`:
    // `darkGreen`/`darkPurple`/`darkPending`/`darkBrown` are INK and must go LIGHTER than their mid
    // siblings, while `lightGreen`/`lightRed`/`lightPending` are FILLS and go dark.
    infoCardBgColor: Color = Color(0xFF101A11),
    groupMemberCardBgColor: Color = Color(0xFF0E140E),
    groupTaskFilterColor: Color = Color(0xFFFF3B3B),
    lightRed: Color = Color(0xFF3A1010),
    red: Color = Color(0xFFE86868),
    crossRed: Color = Color(0xFFFF3B3B),
    heartFull: Color = Color(0xFFFF3B3B),
    heartEmpty: Color = Color(0xFF2A3A28),
    statusCardGray: Color = Color(0xFF6E9E68),
    bgColorPurple: Color = Color(0xFF0F2415),
    bgColor: Color = Color(0xFF050705),
    background: Color = bgColor,
    // One notch above the ground, which is all a scanline ever is.
    gridLine: Color = Color(0xFF0D1A0E),
    onBackground: Color = Color(0xFFC9FFC0),
    surface: Color = Color(0xFF0B120B),
    onSurface: Color = Color(0xFFC9FFC0),
    primary: Color = Color(0xFF39FF14),
    onPrimary: Color = Color(0xFF050705),
    lightPurple: Color = Color(0xFF2E7A3C),
    gray: Color = Color(0xFF6E9E68),
    black: Color = Color(0xFF000000),
    darkPurple: Color = Color(0xFFC98BFF),
    purple: Color = Color(0xFFB14CFF),
    brown: Color = Color(0xFF8FBF88),
    green: Color = Color(0xFF39FF14),
    lightGreen: Color = Color(0xFF06323C),
    mediumGreen: Color = Color(0xFF00E5FF),
    darkGreen: Color = Color(0xFF6FF2FF),
    orange: Color = Color(0xFFFFD400),
    darkBrown: Color = Color(0xFFA8D8A2),
    lightBrown: Color = Color(0xFF1E2C20),
    beige: Color = Color(0xFF141F14),
    lightOrange: Color = Color(0xFF3A2E00),
    lightYellow: Color = Color(0xFF3D3A12),
    lightPending: Color = Color(0xFF0E140E),
    mediumPending: Color = Color(0xFF4A7346),
    pendingGray: Color = Color(0xFF5C9E68),
    darkPending: Color = Color(0xFFA8D8A2),
    white: Color = Color(0xFFEAFFE6),
    softPink: Color = Color(0xFFFF6FD8),
    // The neon hairline. This is the kit's card edge, so it runs brighter than a hairline usually does.
    lightGray: Color = Color(0xFF2E9E3C),
    warmContainer: Color = Color(0xFF2B2200),
    purpleContainer: Color = Color(0xFF241338),
    settingsCard: Color = Color(0xFF0E140E),
    polaroid: PolaroidColors = polaroidColors(),
): TDColor = TDColor(
    infoCardBgColor = infoCardBgColor,
    groupMemberCardBgColor = groupMemberCardBgColor,
    groupTaskFilterColor = groupTaskFilterColor,
    lightRed = lightRed,
    red = red,
    crossRed = crossRed,
    heartFull = heartFull,
    heartEmpty = heartEmpty,
    statusCardGray = statusCardGray,
    bgColorPurple = bgColorPurple,
    bgColor = bgColor,
    background = background,
    gridLine = gridLine,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    primary = primary,
    onPrimary = onPrimary,
    lightPurple = lightPurple,
    gray = gray,
    black = black,
    darkPurple = darkPurple,
    purple = purple,
    brown = brown,
    green = green,
    lightGreen = lightGreen,
    mediumGreen = mediumGreen,
    darkGreen = darkGreen,
    orange = orange,
    darkBrown = darkBrown,
    lightBrown = lightBrown,
    beige = beige,
    lightOrange = lightOrange,
    lightYellow = lightYellow,
    lightPending = lightPending,
    mediumPending = mediumPending,
    pendingGray = pendingGray,
    darkPending = darkPending,
    white = white,
    softPink = softPink,
    lightGray = lightGray,
    warmContainer = warmContainer,
    purpleContainer = purpleContainer,
    settingsCard = settingsCard,
    polaroid = polaroid,
)

@Immutable
data class TDColor(
    val infoCardBgColor: Color,
    val groupMemberCardBgColor: Color,
    val groupTaskFilterColor: Color,
    val lightRed: Color,
    val red: Color,
    val crossRed: Color,
    val heartFull: Color,
    val heartEmpty: Color,
    val statusCardGray: Color,
    val bgColorPurple: Color,
    val bgColor: Color,
    val background: Color,
    val gridLine: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val primary: Color,
    val onPrimary: Color,
    val lightPurple: Color,
    val gray: Color,
    val black: Color,
    val darkPurple: Color,
    val purple: Color,
    val brown: Color,
    val green: Color,
    val lightGreen: Color,
    val mediumGreen: Color,
    val darkGreen: Color,
    val orange: Color,
    val darkBrown: Color,
    val lightBrown: Color,
    val beige: Color,
    val lightOrange: Color,
    val lightYellow: Color,
    val lightPending: Color,
    val mediumPending: Color,
    val pendingGray: Color,
    val darkPending: Color,
    val white: Color,
    val softPink: Color,
    val lightGray: Color,
    val warmContainer: Color,
    val purpleContainer: Color,
    val settingsCard: Color,
    val polaroid: PolaroidColors,
)
